apiVersion: v1
kind: Secret
metadata:
  name: seckill-db-secret
  namespace: seckill
type: Opaque
stringData:
  DB_HOST: "seckill-postgres.seckill.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "seckill"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres123"
